import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import Providers from "./provider";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";

const dmSans = DM_Sans({
  subsets : ["latin"],
  display : "swap",
  variable : "--font-dm-sans"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${dmSans.className}`}
      >
        <Providers>
          <div className="root-layout">
            <Toaster richColors closeButton />
            {children}
          </div>
        </Providers>
      </body>
    </html>
    </ClerkProvider>
  );
}
